// Minecraft bitmap font renderer for the browser.
// Loads the font atlas extracted from the MC JAR (assets/font/ascii.png) and the
// per-character advance-width table (assets/font/minecraft-font-widths.json), then
// renders text to an off-screen canvas with correct Minecraft character spacing.
//
// If the assets haven't been extracted yet, all functions fall back gracefully.

type FontData = { atlas: HTMLImageElement; widths: number[] }

let fontData: FontData | null = null
let fontLoadPromise: Promise<FontData | null> | null = null

function loadImg(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve(img)
    img.onerror = reject
    img.src = src
  })
}

// Attempts to load the extracted Minecraft font assets. Returns true on success.
// Safe to call multiple times — only fetches once.
export async function loadMinecraftFont(assetURL = 'assets/'): Promise<boolean> {
  if (fontData) return true
  if (!fontLoadPromise) {
    fontLoadPromise = Promise.all([
      loadImg(assetURL + 'font/ascii.png'),
      fetch(assetURL + 'font/minecraft-font-widths.json').then(r => r.ok ? r.json() as Promise<number[]> : null),
    ]).then(([atlas, widths]) => {
      if (!widths) return null
      return { atlas, widths }
    }).catch(() => null)
  }
  const result = await fontLoadPromise
  if (result) fontData = result
  return !!result
}

export function isFontLoaded(): boolean {
  return !!fontData
}

// Returns the total rendered width in HUD pixels for the given text at the given size scale.
// Minecraft inserts 1 px between characters; no trailing gap.
export function measureMinecraftText(text: string, size: number): number {
  if (!fontData) return text.split('\n').reduce((m, l) => Math.max(m, l.length), 0) * 6 * size
  const { widths } = fontData
  let maxW = 0
  for (const line of text.split('\n')) {
    let w = 0
    for (const ch of line) {
      const code = ch.charCodeAt(0)
      w += (code === 32 ? 3 : (widths[code] ?? 6)) + 1
    }
    maxW = Math.max(maxW, Math.max(0, w - 1))
  }
  return maxW * size
}

// Renders Minecraft bitmap text onto canvas, resizing it to fit the text exactly.
// color: 24-bit 0xRRGGBB. alpha: 0–255.
// No-ops if the font hasn't been loaded yet.
export function renderMinecraftTextToCanvas(
  canvas: HTMLCanvasElement,
  text: string,
  size: number,
  color: number,
  alpha: number,
): void {
  if (!fontData) return
  const { atlas, widths } = fontData

  const CELL = 8   // px per char cell in the 128×128 atlas
  const GAP  = 1   // Minecraft inter-character gap

  const lines  = text.split('\n')
  const totalW = measureMinecraftText(text, size)
  const totalH = lines.length * 9 * size  // 8 px glyph + 1 px descender row per line

  canvas.width  = Math.max(1, Math.round(totalW))
  canvas.height = Math.max(1, Math.round(totalH))

  const ctx = canvas.getContext('2d')
  if (!ctx) return
  ctx.clearRect(0, 0, canvas.width, canvas.height)

  // Draw white glyphs from the atlas
  const tmp = document.createElement('canvas')
  tmp.width = canvas.width; tmp.height = canvas.height
  const tc = tmp.getContext('2d')
  if (!tc) return
  tc.imageSmoothingEnabled = false

  for (let li = 0; li < lines.length; li++) {
    const lineY = Math.round(li * 9 * size)
    let cx = 0
    for (const ch of lines[li]) {
      const code = ch.charCodeAt(0)
      // Space advance = 4 px total in Minecraft. Our loop adds 1 gap after every char,
      // so the stored width must be 3. If this JSON was generated by an older extractor
      // run that stored 4, we correct it here.
      const w = code === 32 ? 3 : (widths[code] ?? 6)
      const row  = code >> 4
      const col  = code & 0xF
      tc.drawImage(atlas,
        col * CELL, row * CELL, w, CELL,                                              // src: exactly 8 px glyph rows
        Math.round(cx * size), lineY, Math.round(w * size), Math.round(CELL * size), // dst: line offset
      )
      cx += w + GAP
    }
  }

  // Tint: multiply atlas RGB channels by the target color, scale alpha
  const r = (color >> 16) & 0xFF
  const g = (color >>  8) & 0xFF
  const b =  color        & 0xFF
  const imgData = tc.getImageData(0, 0, canvas.width, canvas.height)
  const d = imgData.data
  for (let i = 0; i < d.length; i += 4) {
    d[i]     = Math.round(d[i]     * r / 255)
    d[i + 1] = Math.round(d[i + 1] * g / 255)
    d[i + 2] = Math.round(d[i + 2] * b / 255)
    d[i + 3] = Math.round(d[i + 3] * alpha / 255)
  }
  ctx.putImageData(imgData, 0, 0)
}
