-- =============================================================================
-- ARCHIVE: Modem-Forwarding Pattern (removed)
-- =============================================================================
-- Previously, client computers (turtles, minecarts, players, stationary) sent
-- all outbound data (state, scan, sense, chat, commandResult, statusUpdate) to
-- the modem server via wireless modem, and the modem server forwarded each
-- message as an HTTP request to the web server.
--
-- This was changed so that clients send outbound data directly to the HTTP
-- server themselves. The modem server now only handles what it uniquely provides:
-- polling the HTTP server for pending commands and broadcasting them to clients.
--
-- Reason for removal: the forwarding path had silent drop risks — HTTP failures
-- from forward_to_server were not logged or retried, CC's concurrent HTTP cap
-- could silently discard excess requests, and the CC event queue could overflow
-- under a burst of modem_message events from multiple turtles at once.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- modemServer.lua — removed pieces
-- -----------------------------------------------------------------------------

-- -- Mapping of modem message type → HTTP endpoint path.
-- local endpoint_map = {
--   state         = "state",
--   scan          = "scan",
--   sense         = "sense",
--   chat          = "chat",
--   commandResult = "commandResult",
--   statusUpdate  = "statusUpdate",
-- }

-- -- Fire-and-forget: forward a modem message to the HTTP server.
-- -- Also auto-registered the sending computer into served_ids so the modem
-- -- would start polling commands for it without needing a restart.
-- local function forward_to_server(message)
--   local computer_id = message.data and (message.data.id or message.data.computerId)
--   if computer_id and not served_ids[computer_id] then
--     served_ids[computer_id] = true
--     print("+ registered computer " .. tostring(computer_id))
--   end
--
--   local endpoint = endpoint_map[message.type]
--   if not endpoint or not message.data then return end
--   local json = textutils.serializeJSON(message.data)
--   http.request(BASE_URL .. endpoint, json, headers)
-- end

-- -- In the main event loop — handled every inbound modem packet:
-- elseif event == "modem_message" then
--   local message = p4
--   if type(message) == "table" then
--     forward_to_server(message)
--   end


-- -----------------------------------------------------------------------------
-- tapi / capi / papi / sapi — removed modem-transmit branches
-- -----------------------------------------------------------------------------
-- Every outbound send function previously had this pattern:
--
--   if use_modem then
--     modem_device.transmit(MODEM_SERVER_ID, os.getComputerID(),
--       { type = "<msgType>", data = <payload> })
--   else
--     local json = textutils.serializeJSON(<payload>)
--     http.request / http.post(url .. "<endpoint>", json, headers)
--   end
--
-- The modem branch has been removed from all of the following functions:
--   tapi  : send_status_update, send_command_result, scan
--   capi  : send_status_update, send_command_result, scan, sense, send_chat
--   papi  : send_status_update, send_command_result, scan
--   sapi  : send_status_update, send_command_result, send_chat, sense
--
-- use_modem is still set at startup (by the modem-id discovery in each API) and
-- is still read by the rcXxx event loops to decide whether to listen on the
-- modem or poll HTTP for inbound commands. Only the outbound (client→server)
-- path is affected.
